# Generated by Django 2.0.9 on 2018-11-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0002_contact_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupContractMap',
            new_name='GroupContactMap',
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
