# Generated by Django 2.0.9 on 2018-11-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0003_auto_20181105_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcontactmap',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='groupcontactmap',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='groupcontactmap',
            name='group',
        ),
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cmc.Group'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GroupContactMap',
        ),
    ]
