# Generated by Django 2.0.9 on 2018-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0005_auto_20181107_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='vasuse7en@gmail.com', max_length=70),
            preserve_default=False,
        ),
    ]
